[project]
name = "test_suite"
version = "0.0.0"

[dependencies]
bitflags = { path = "../" }
trybuild = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[features]
default = []
const_operator = ["bitflags/const_operator"]
